app/home/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import datetime
from time import timezone

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, DateTimeField
from wtforms.validators import DataRequired, Email, Regexp, EqualTo, ValidationError

# 用户注册表单
from app.models import User


class RegisterForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("昵称不能为空！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
            # "required":"required"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("手机号不能为空！"),
            Regexp("1[3458]\d{9}", message="手机格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机！",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('pwd', message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码！",
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "style": "margin-right:20px; margin-top:20px;"
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号码已经存在！")


class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("账号不能为空！")
        ],
        description="账号",
        render_kw={
            "class": "btn",
            "placeholder": "请输入账号！",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "class": "btn",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn",
        }
    )


class UserForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("昵称不能为空！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号（昵称）！",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("手机号不能为空！"),
            Regexp("1[3458]\d{9}", message="手机格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号码！",
        }
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("简介不能为空！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 10
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="原密码",
        validators=[
            DataRequired("原密码不能为空！")
        ],
        description="原密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入原密码！",
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("新密码不能为空！"),
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！",
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            "class": "btn btn-success",
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="电影评论",
        validators=[
            DataRequired("请输入此电影的评论")
        ],
        description="电影评论",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入相关的电影评论",
            # 'required':"required"
        }
    )

    submit = SubmitField(
        "提交评论",
        render_kw={
            "class": "btn btn-success",
        }
    )


class UserRecommedFrom(FlaskForm):
    '''用户推荐'''
    title = StringField(
        label="电影名称",
        description="电影名称",
        validators=[
            DataRequired("请填写需要推荐的电影名")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "请输入需要填写的电影名称电影名称"
        }
    )
    protagonist = StringField(label="主演", validators=[DataRequired("请填写电影主演")],render_kw={"placeholder":"请填写电影主演","class": "form-control",})

    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("简介不能为空！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 2,
            "placeholder": "电影简介"
        }
    )

    area = StringField(
        label="上映地区",
        validators=[
            DataRequired("请填写上映地区")
        ],
        description="上映地区",
        render_kw={
            "class": "form-control",
            "placeholder": "上映地区"
        }
    )

    release_time = StringField(
        label="上映时间",
        validators=[
            DataRequired("请填写上映时间")
        ],
        description="上映时间",
        render_kw={
            "class": "form-control",
            "placeholder": "上映时间"
        },
        default=datetime.now()
    )
    submit = SubmitField(
        "确认推荐",
        render_kw={
            "class": "btn btn-success",
        }

    )

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import urllib
import uuid
import time
import json
import os
from functools import wraps
from datetime import datetime

from alipay import AliPay
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from app.home.forms import RegisterForm, LoginForm, UserForm, PwdForm, CommentForm, UserRecommedFrom
from app.models import User, Userlog, Preview, Tag, Movie, Comment, Moviecol, UserRecommend
from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response


def cache_key():
    args = request.args
    key = request.path + '?' + urllib.parse.urlencode([
        (k, v) for k in sorted(args) for v in sorted(args.getlist(k))
    ])
    return key


# 用户登陆装饰器
def user_login_check(func):
    @wraps(func)
    def check(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("home.login", next=request.url))
        return func(*args, **kwargs)

    return check


@home.route("/login/", methods=["GET", "POST"])
def login():
    '''
    用户登陆
    '''
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        name = data["name"]
        user = User.query.filter_by(name=name).first()
        if user:
            if check_password_hash(user.pwd, form.pwd.data):
                # 记录登陆信息
                session["user"] = user.name
                session["user_id"] = user.id

                # 用户登陆日志
                userlog = Userlog(
                    user_id=user.id,
                    # ip=request.headers['X-Real-IP']
                    ip=request.remote_addr
                )
                db.session.add(userlog)
                db.session.commit()

                return redirect(url_for("home.index", page=1))
            else:
                flash("密码错误请重试", "success")
                return redirect(url_for("home.login"))
        else:
            flash("用户未注册，请先进行注册", "success")
            time.sleep(5)
            return redirect(url_for("home.register"))
    return render_template("home/login2.html", form=form)


@home.route("/logout/")
@user_login_check
def logout():
    '''
    用户退出登陆
    '''
    session.pop("user")
    session.pop("user_id")
    return redirect(url_for("home.login"))


@home.route("/register/", methods=["GET", "POST"])
def register():
    '''
    注册
    '''
    form = RegisterForm(request.form)
    tt = form.name.data
    count = User.query.filter_by(name=tt).count()
    if count == 0 and form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            email=data["email"],
            phone=data["phone"],
            pwd=generate_password_hash(data["pwd"]),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        # flash("注册成功！", "ok")
        return redirect(url_for("home.login"))
    # flash("用户名已存在，请重新注册新的用户名")
    return render_template("home/register1.html", form=form)


@home.route("/user/", methods=["GET", "POST"])
@user_login_check
def user():
    '''
    用户信息
    '''
    user = User.query.filter_by(id=session["user_id"]).first()
    form = UserForm()
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info

    if form.validate_on_submit():
        new_name = form.name.data
        if User.query.filter_by(name=new_name).first():
            flash("用户名已存在", "success")
            return redirect(url_for("home.user"))

        user.name = new_name
        user.email = form.email.data
        user.phone = form.phone.data
        user.info = form.info.data

        db.session.add(user)
        db.session.commit()
        flash("用户信息已修改", "success")
    return render_template("home/user.html", form=form, user=user)


@home.route("/pwd/", methods=["GET", "POST"])
@user_login_check
def pwd():
    '''
    修改密码
    '''
    user = User.query.filter_by(id=session["user_id"]).first()
    form = PwdForm()
    if form.validate_on_submit():
        old_pwd = form.old_pwd.data
        if check_password_hash(user.pwd, old_pwd):
            user.pwd = generate_password_hash(form.new_pwd.data)
            db.session.add(user)
            db.session.commit()
            flash("密码已修改,请重新登陆", "success")
            return redirect(url_for("home.login"))
        else:
            flash("原密码错误，请输入正确的密码", "fail")
            return redirect(url_for("home.pwd"))
    return render_template("home/pwd.html", form=form)


@home.route("/comments/", methods=["GET"])
@user_login_check
def comments():
    '''
    用户评论
    '''
    comment_list = Comment.query.filter_by(user_id=session["user_id"]).order_by(Comment.addtime.desc()).limit(7)
    return render_template("home/comments.html", comment_list=comment_list)


@home.route("/loginlog/", methods=["GET"])
@user_login_check
def loginlog():
    # 查询用户登陆日志 且只显示最近的五次登陆
    user_log = Userlog.query.filter_by(user_id=session["user_id"]).order_by(Userlog.addtime.desc()).limit(5)
    return render_template("home/loginlog.html", user_log=user_log)


@home.route("/moviecol/add/", methods=["GET", 'POST'])
@user_login_check
def moviecol_add():
    '''
    用户电影收藏
    :return:
    '''
    movie_id = request.args.get("mid", "")
    user_id = request.args.get("uid", "")
    movie_col = Moviecol.query.filter_by(movie_id=movie_id, user_id=user_id).first()
    if movie_col:
        # 已收藏
        data = json.dumps(dict(status=0))
        return data
    else:
        moviecol = Moviecol(
            movie_id=movie_id,
            user_id=user_id,
        )
        db.session.add(moviecol)
        db.session.commit()

        data = json.dumps(dict(status=1))
        return data


@home.route("/moviecol/<int:page>", methods=['GET'])
@user_login_check
def moviecol(page):
    '''
    电影收藏
    '''
    if page is None:
        page = 1
    user_collection = Moviecol.query.join(User).filter(User.id == session["user_id"]).order_by(
        Moviecol.addtime.desc()).paginate(page=page, per_page=5)
    # count = Moviecol.query.join(User).filter(User.id == session["user_id"]).order_by(
    #     Moviecol.addtime.desc()).count()
    return render_template("home/moviecol.html", user_collection=user_collection)


@home.route("/moviecol/del/<int:movie_id>", methods=['GET'])
@user_login_check
def moviecol_del(movie_id):
    '''
    电影收藏删除
    '''
    movie_col = Moviecol.query.filter_by(movie_id=movie_id).first()
    db.session.delete(movie_col)
    db.session.commit()
    flash("收藏已删除", "success")
    return redirect(url_for("home.moviecol", page=1))


@home.route("/index/<int:page>", methods=["GET"])
def index(page):
    '''
    首页
    '''
    tags = Tag.query.all()
    page_data = Movie.query
    # print(page_data)
    # 标签
    tid = request.args.get("tid", '')
    if tid:
        page_data = page_data.filter_by(tag_id=tid)
    # 星级
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
        # print('='*30)
        # for i in page_data:
        #     print(i)
        #     print(i.tag_id)
    # 时间
    time = request.args.get("time", 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    # 播放量
    pm = request.args.get("pm", 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论量
    cm = request.args.get("cm", 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.commentnum.asc()
            )
    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=8)
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm,
    )

    # 对电影表进行查询 选出符合条件的热门电影 2-11的电影
    movie_list = Movie.query.order_by(Movie.playnum.desc()).offset(1).limit(10).all()
    movie_special = Movie.query.order_by(Movie.playnum.desc()).first()
    movie_top = Movie.query.order_by(Movie.commentnum.desc()).limit(8)

    return render_template("home/index.html", tags=tags, p=p, page_data=page_data, movie_list=movie_list,
                           movie_top=movie_top, movie_special=movie_special)


@home.route("/", methods=["GET"])
def index1():
    return redirect(url_for("home.index", page=1))


@home.route("/search_click/", methods=['GET'])
def click_search():
    '''
    多条件筛选
    '''
    return redirect(url_for('home.search_show', page=1))


@home.route("/search_show/<int:page>", methods=['GET', 'POST'])
def search_show(page):
    '''
    多条件筛选
    '''
    tags = Tag.query.all()
    page_data = Movie.query
    # print(page_data)
    # 标签
    tid = request.args.get("tid", '')
    if tid:
        page_data = page_data.filter_by(tag_id=tid)
    # 星级
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
        # print('='*30)
        # for i in page_data:
        #     print(i)
        #     print(i.tag_id)
    # 时间
    time = request.args.get("time", 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    # 播放量
    pm = request.args.get("pm", 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>看视频</title>
    {#    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">#}
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">#}
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">#}
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">#}

    <link rel="shortcut icon" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/images/logo.png">
    <link rel="stylesheet" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/css/bootstrap-movie.css">
    <link rel="stylesheet" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/css/animate.css">
    {#    <link rel="stylesheet" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/font-awesome-4.7.0/css/font-awesome.min.css">#}
    <style>
        .navbar-brand > img {
            display: inline;
        }

    </style>
    <style>
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1 ) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;嘿--看视频
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for("home.show_recommend",page=1) }}"><i class="fa fa-hand-paper-o"
                                                                                             aria-hiddens="true"></i>&nbsp;用户推荐</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if session['user'] %}

                {% else %}
                    <li hidden="hidden">
                        <a class="curlink" href="{{ url_for('home.login') }}"><span
                                class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li hidden="hidden">
                        <a class="curlink" href="{{ url_for('home.register') }}"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                {% endif %}
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.user") }}"><span class="glyphicon glyphicon-user"></span>&nbsp;用户中心</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align: center">
                <p>
                    网站资源均为爬虫爬取，如有侵权请联系站长进行删除。
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
{#<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>#}
{#<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>#}
{#<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>#}
{#<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>#}

<script src="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/js/jquery.min.js"></script>
<script src="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/js/bootstrap.min.js"></script>
<script src="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/js/jquery.singlePageNav.min.js"></script>
<script src="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/base/js/wow.min.js"></script>

<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

    $("#do_search").click(function () {
        var key = $("#key_movie").val();
        location.href = "{{ url_for("home.search", page=1) }}?key=" + key
    });

</script>
{% block js %}
{% endblock %}
</body>
</html>

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;用户中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments') }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog') }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
        <a id="m-5" href="{{ url_for("home.my_recommend") }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;我的推荐
        </a>
    </div>
</div>

{#<div class="col-md-3">#}
{#    <div class="list-group">#}
{#        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 50px;">#}
{#            <legend>面板嵌套</legend>#}
{#        </fieldset>#}
{#        <div class="layui-collapse" lay-accordion="">#}
{#            <div class="layui-colla-item">#}
{#                <h2 class="layui-colla-title">文豪</h2>#}
{#                <div class="layui-colla-content layui-show">#}
{##}
{#                    <div class="layui-collapse" lay-accordion="">#}
{#                        <div class="layui-colla-item">#}
{#                            <h2 class="layui-colla-title">唐代</h2>#}
{#                            <div class="layui-colla-content layui-show">#}
{##}
{#                                <div class="layui-collapse" lay-accordion="">#}
{#                                    <div class="layui-colla-item">#}
{#                                        <h2 class="layui-colla-title">杜甫</h2>#}
{#                                        <div class="layui-colla-content layui-show">#}
{#                                            伟大的诗人#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="layui-colla-item">#}
{#                                        <h2 class="layui-colla-title">李白</h2>#}
{#                                        <div class="layui-colla-content">#}
{#                                            <p>据说是韩国人</p>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="layui-colla-item">#}
{#                                        <h2 class="layui-colla-title">王勃</h2>#}
{#                                        <div class="layui-colla-content">#}
{#                                            <p>千古绝唱《滕王阁序》</p>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{##}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="layui-colla-item">#}
{#                            <h2 class="layui-colla-title">宋代</h2>#}
{#                            <div class="layui-colla-content">#}
{#                                <p>比如苏轼、李清照</p>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="layui-colla-item">#}
{#                            <h2 class="layui-colla-title">当代</h2>#}
{#                            <div class="layui-colla-content">#}
{#                                <p>比如贤心</p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <div class="layui-colla-item">#}
{#                <h2 class="layui-colla-title">科学家</h2>#}
{#                <div class="layui-colla-content">#}
{#                    <p>伟大的科学家</p>#}
{#                </div>#}
{#            </div>#}
{#            <div class="layui-colla-item">#}
{#                <h2 class="layui-colla-title">艺术家</h2>#}
{#                <div class="layui-colla-content">#}
{#                    <p>浑身散发着艺术细胞</p>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

app/templates/home/slider-layui.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>轮播图</title>
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='layui/css/layui.css') }}" media="all">#}
    <link rel="stylesheet" href="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/layui/css/layui.css"
          media="all">
</head>
<body>

<div class="layui-carousel" id="test1">
    <div carousel-item>
        {% for i in data %}
            <div><img src="{{ url_for('static', filename='uploads/'+ i.logo) }}" alt="{{ i.name }}"></div>
        {% endfor %}
    </div>
</div>
<!-- 条目中可以是任意内容，如：<img src=""> -->

{#<script src="{{ url_for('static', filename='layui/layui.js') }}"></script>#}
<script src="http://person-movie.oss-cn-shenzhen.aliyuncs.com/static/layui/layui.js"></script>
<script>
    layui.use('carousel', function () {
        var carousel = layui.carousel;
        //建造实例
        carousel.render({
            elem: '#test1'
            , width: '100%' //设置容器宽度
            , height: '380px'
            , arrow: 'always' //始终显示箭头
            //,anim: 'updown' //切换动画方式
            , autoplay: true
        });
    });
</script>
</body>
</html>